spring:
  application:
    name: revendedora-api
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate   # schema e 100% controlado pelo Flyway, JPA so valida
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:chave-secreta-temporaria-troque-isso-em-producao-com-256-bits-no-minimo}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
